
name: Continuous Integration

on:
  pull_request:
    branches: [ "main" ]

jobs:
  Ci_Verification:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Test Complains Service
      working-directory: ./complains
      run: |
        npm ci
        npm test
    
    - name: Test Article Service
      working-directory: ./article
      run: |
        npm ci
        npm test

    - name: Test Feedback Service
      working-directory: ./feedback
      run: |
        npm ci
        npm test

    - name: Test User Service
      working-directory: ./user
      run: |
        npm ci
        npm test


   
